### PR TITLE
Disable analytics if connection to google is not available

### PR DESCRIPTION
**Pull request by hartmark**
I have blocked google analytics on dns-level so the application crashes because it tries to connect to google and to opt out you need to first launch program.

### CODE REVIEW

**Comment by aleab** [comment]
Nice catch!

**Comment by hartmark** [comment]
made the message a info instead

**Comment by aleab** [comment]
Sorry, my bad. I meant that I prefer to not show the message at all, since it seems intrusive, but rather just write the error message to the log file.

One of the following should be good:
```C#
logger.Info("Couldn't reach google, disabling Analytics", e);

logger.Warn("Couldn't reach google, disabling Analytics", e);
```

**Comment by hartmark** [comment]
haha, aha.. alright.. I fix

**Comment by hartmark** [comment]
alright, third time is the charm

**Comment by aleab** [comment]
That's what they say. 😄
Sorry for the hassle. Now it's perfect! 👍

**Pull request merged**
